[package]
name = "ahc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitset-fixed = "0.1.0"
fixedbitset = "0.5.7"
itertools = "0.14.0"
num-complex = "0.4.6"
num-traits = "0.2.19"
rand = "0.9.2"
rand_distr = "0.5.1"
rand_pcg = "0.9.0"
omniswap = "0.1.0"
ordered-float = "5.0.0"
proconio = "0.5.0"
recur-fn = "2.2.0"
rustc-hash = "2.1.1"

[features]
default = ["local"]
local = []
